version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # checks workflow files in ".github/workflows"
    schedule:
      interval: "monthly"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dev:
        dependency-type: "development"
        patterns:
          - "*"
