name: push to main branch

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  test:
    uses: ./.github/workflows/test.yaml

  release-please:
    name: release-please
    needs: [ lint, test ]
    permissions:
      issues: write
      contents: write
      pull-requests: write
    secrets: inherit
    uses: ./.github/workflows/release-please.yaml

  build:
    name: Build Package
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set up Python (uv)
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true

      - name: Build
        run: uv build

      - name: Upload Package Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: rock-physics-open-distribution
          path: dist/

  publish:
    name: Publish Package to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/rock-physics-open
    permissions:
      id-token: write # required for trusted publishing to PyPI

    steps:
      - name: Download Package Artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: rock-physics-open-distribution
          path: dist/

      - name: Publish Package to PyPI
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1
