name: test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        os: [windows-latest, ubuntu-latest, macos-latest]
        module-resolution: ["uv.lock"]
        # to ensure the "most outdated" versions still work
        include:
          - os: windows-latest
            python-version: "3.11"
            module-resolution: lowest
          - os: ubuntu-latest
            python-version: "3.11"
            module-resolution: lowest
          - os: macos-latest
            python-version: "3.11"
            module-resolution: lowest

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.python-version }} - ${{ matrix.os }}${{ matrix.module-resolution == 'lowest' && ' (lowest)' || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python (uv)
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: false

      - name: Install dependencies
        run: uv sync ${{ matrix.module-resolution == 'uv.lock' && '--locked' || '--resolution=lowest-direct' }}

      - name: Run pytest
        run: uv run --no-sync pytest
