name: test
permissions:
  contents: read

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade Pip
      run: pip install --upgrade pip

    - name: Show Machine Information
      run: |
        pip install py-cpuinfo
        python -m cpuinfo

    - name: Install Dependencies
      run: pip install .[tests]

    - name: Test
      if: ${{ matrix.os == 'windows-latest' }}
      run: pytest

    - name: Test ( -m "not use_graphics" )
      if: ${{ matrix.os != 'windows-latest' }}
      run: pytest -m "not use_graphics"
